/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./*.html', './js/**/*.js'],
  theme: {
    extend: {
      colors: {
        "surface-container": "#edeef0",
        "inverse-primary": "#c9c6c5",
        "inverse-on-surface": "#f0f0f2",
        "tertiary-fixed": "#006875",
        "on-surface-variant": "#474747",
        "tertiary-container": "#008190",
        "surface-container-high": "#e8e8ea",
        "surface-container-low": "#f3f3f5",
        "surface-tint": "#5f5e5e",
        "on-error-container": "#410002",
        "primary": "#000000",
        "on-tertiary-fixed-variant": "#9cf0ff",
        "primary-fixed-dim": "#474646",
        "on-primary-fixed-variant": "#e5e2e1",
        "secondary": "#5e5e63",
        "on-primary-fixed": "#ffffff",
        "background": "#f9f9fb",
        "on-tertiary-fixed": "#ffffff",
        "surface-variant": "#e2e2e4",
        "surface-dim": "#d9dadc",
        "primary-container": "#3c3b3b",
        "on-secondary-fixed": "#1a1b1f",
        "outline-variant": "#c6c6c6",
        "on-primary": "#e5e2e1",
        "secondary-fixed": "#c7c6cb",
        "on-secondary-fixed-variant": "#3a3b40",
        "on-primary-container": "#ffffff",
        "surface-container-highest": "#e2e2e4",
        "tertiary": "#00424b",
        "outline": "#777777",
        "error": "#ba1a1a",
        "primary-fixed": "#5f5e5e",
        "secondary-fixed-dim": "#ababb0",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f3132",
        "on-tertiary": "#9cf0ff",
        "secondary-container": "#d5d4d9",
        "on-tertiary-container": "#ffffff",
        "surface": "#f9f9fb",
        "surface-bright": "#f9f9fb",
        "tertiary-fixed-dim": "#004f58",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1d",
        "on-secondary-container": "#1a1b1f",
        "on-background": "#1a1c1d",
        "accent-cyan": "#00E5FF",
        "body-grey": "#86868B",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
};
